name: Build

on:
  push:
    tags:
      - '1.*.*'
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Package Source
        run: |
          tar -czf release-${{ env.RELEASE_VERSION }}.tar.gz lambda_function.py requirements.txt makefile

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-${{ env.RELEASE_VERSION }}
          path: release-${{ env.RELEASE_VERSION }}.tar.gz

      - name: Make Release
        uses: softprops/action-gh-release@v0.1.5
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: release-${{ env.RELEASE_VERSION }}
          files: |
            release-${{ env.RELEASE_VERSION }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}